default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: find_a_friend_development

test:
  <<: *default
  database: find_a_friend_test

production:
  <<: *default
  database: find_a_friend
  username: dcox
  password: <%= ENV['FINDFRIEND_DATABASE_PASSWORD'] %>
